import { Property, ChatMessage, AnalysisResult } from '@/types';

export const mockProperties: Property[] = [
    {
        id: '1',
        title: 'Modern 3-Bed Condo — Upper East Side',
        location: 'Upper East Side, New York, NY',
        price: '$1.25M',
        priceValue: 1250000,
        image: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800&q=80',
        beds: 3,
        baths: 2,
        sqft: 1650,
        description: 'Beautifully designed condo with premium finishes, doorman, covered parking, and stunning city views from the 12th floor.',
        type: 'Apartment',
        tags: ['Ready to Move', 'Gated Community'],
        url: 'https://www.zillow.com/homedetails/1',
    },
    {
        id: '2',
        title: 'Luxury Villa with Pool — Beverly Hills',
        location: 'Beverly Hills, CA',
        price: '$4.8M',
        priceValue: 4800000,
        image: 'https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=800&q=80',
        beds: 5,
        baths: 4,
        sqft: 4200,
        description: 'Stunning villa with private pool, landscaped garden, smart home automation, and a dedicated home theatre. Ideal for luxury living.',
        type: 'Villa',
        tags: ['Luxury', 'Swimming Pool'],
        url: 'https://www.zillow.com/homedetails/2',
    },
    {
        id: '3',
        title: 'Prime Commercial Office — Downtown Chicago',
        location: 'The Loop, Chicago, IL',
        price: '$2.3M',
        priceValue: 2300000,
        image: 'https://images.unsplash.com/photo-1497366216548-37526070297c?w=800&q=80',
        beds: 0,
        baths: 3,
        sqft: 2200,
        description: "Class-A commercial space in Chicago's prime business district. High-speed elevators, backup power, and conference facilities included.",
        type: 'Commercial',
        tags: ['Commercial', 'Business District'],
        url: 'https://www.loopnet.com/Listing/3',
    },
    {
        id: '4',
        title: 'Cozy 3-Bed Family Home — Austin',
        location: 'Round Rock, Austin, TX',
        price: '$520K',
        priceValue: 520000,
        image: 'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800&q=80',
        beds: 3,
        baths: 2,
        sqft: 1800,
        description: 'Well-maintained family home in a quiet suburb with a spacious backyard, two-car garage, and great school district ratings.',
        type: 'House',
        tags: ['Family Home', 'Garden'],
        url: 'https://www.zillow.com/homedetails/4',
    },
    {
        id: '5',
        title: 'Studio Apartment — South Beach Miami',
        location: 'South Beach, Miami, FL',
        price: '$380K',
        priceValue: 380000,
        image: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&q=80',
        beds: 1,
        baths: 1,
        sqft: 650,
        description: 'Modern studio apartment ideal for singles or investors. Fully furnished, steps from the beach, excellent short-term rental yield.',
        type: 'Apartment',
        tags: ['Investment', 'Furnished'],
        url: 'https://www.zillow.com/homedetails/5',
    },
    {
        id: '6',
        title: 'Penthouse Suite — Midtown Manhattan',
        location: 'Midtown Manhattan, New York, NY',
        price: '$7.2M',
        priceValue: 7200000,
        image: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&q=80',
        beds: 4,
        baths: 4,
        sqft: 5500,
        description: 'Exclusive penthouse spanning the entire 25th floor. Private rooftop terrace, panoramic skyline views, jacuzzi, and concierge service.',
        type: 'Penthouse',
        tags: ['Skyline View', 'Ultra Luxury'],
        url: 'https://www.zillow.com/homedetails/6',
    },
];

export const initialMessages: ChatMessage[] = [
    {
        id: 'init-1',
        role: 'ai',
        content: "👋 Welcome to **EstateAI** — your intelligent real estate advisor.\n\nI can help you:\n• **Search** properties by location, budget, and type\n• **Analyze** investment potential and ROI\n• **Calculate** mortgage payments for any property\n• **Compare** multiple listings side-by-side\n\nTry asking: *\"Find me a 3 bedroom apartment in New York under $1.5M\"*",
        timestamp: new Date('2024-01-01T00:00:00.000Z'),
    },
];

export const sampleAnalysis: AnalysisResult = {
    propertyTitle: 'Modern 3-Bed Condo — Upper East Side',
    price: 1250000,
    monthlyEMI: 5820,
    totalRental: 54000,
    valueAfter5Yr: 1562500,
    roi: 8.4,
    downPayment: 250000,
    loanAmount: 1000000,
};

export const aiResponses = [
    {
        trigger: ['new york', '3 bed', 'apartment', 'manhattan', 'nyc'],
        message: "I found **3 excellent properties** matching your criteria in New York. All are within your $1.5M budget with top-rated amenities. Check the results panel on the right! →",
        showProperties: true,
        propertyIds: ['1', '4', '5'],
    },
    {
        trigger: ['mortgage', 'calculate', 'payment', 'emi'],
        message: "Here's the **mortgage breakdown** for Upper East Side Condo at $1.25M (30-year loan @ 7.25% p.a., 20% down payment):",
        showAnalysis: true,
        analysisData: {
            propertyTitle: 'Modern 3-Bed Condo — Upper East Side',
            price: 1250000,
            monthlyEMI: 5820,
            totalRental: 54000,
            valueAfter5Yr: 1562500,
            roi: 8.4,
            downPayment: 250000,
            loanAmount: 1000000,
        },
    },
    {
        trigger: ['roi', 'invest', 'return', 'analysis'],
        message: "📊 Here's the **Investment Analysis** for Beverly Hills Villa. With current market trends, this property shows strong appreciation potential:",
        showAnalysis: true,
        analysisData: {
            propertyTitle: 'Luxury Villa — Beverly Hills',
            price: 4800000,
            monthlyEMI: 22340,
            totalRental: 192000,
            valueAfter5Yr: 6240000,
            roi: 9.2,
            downPayment: 960000,
            loanAmount: 3840000,
        },
    },
    {
        trigger: ['beverly hills', 'los angeles', 'california', 'villa', 'la'],
        message: "I've found **2 premium properties** in the Greater LA area matching your search. Both offer excellent appreciation potential in one of California's most sought-after markets.",
        showProperties: true,
        propertyIds: ['2', '6'],
    },
    {
        trigger: ['chicago', 'commercial', 'office', 'illinois'],
        message: "Here are the **top commercial properties** available in Chicago's prime business zones. The Loop continues to see significant demand from businesses.",
        showProperties: true,
        propertyIds: ['3', '5'],
    },
];

export const fallbackResponse = {
    message: "I understand you're looking for properties. Could you share more details?\n\n• **Location** — Which city or state?\n• **Budget** — What's your price range in USD?\n• **Type** — Apartment, house, villa, or commercial?\n• **Size** — How many bedrooms do you need?\n\nThe more details you share, the better I can match you with the perfect property! 🏠",
    showProperties: false,
};
